# Generated by Django 4.0.2 on 2022-03-12 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(default=datetime.datetime(2022, 3, 12, 11, 17, 0, 547243, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
